server:
  port: 8081

langchain4j.community.dashscope.chat-model.api-key: ${aliQwen-api}
langchain4j.community.dashscope.chat-model.model-name: qwen-max
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
  datasource:
    url: jdbc:mysql://localhost:3306/yisagent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 111



es:
  index-name: yis-index-3
  host: localhost
  port: 9200


#集成阿里通义千问-通用文本向量-v3
langchain4j.community.dashscope.embedding-model.api-key: ${aliQwen-api}
langchain4j.community.dashscope.embedding-model.model-name: text-embedding-v3

#集成阿里通义千问-流式输出
langchain4j.community.dashscope.streaming-chat-model.api-key: ${aliQwen-api}
langchain4j.community.dashscope.streaming-chat-model.model-name: qwen-plus
